Added options propagation
kevva/decompress-tarbz2 pull request #6
Opened 2017-02-02 14:47 UTC by Xflofoxx

Added options propagation.

2017-02-02 15:01 UTC, SamVerschueren requested changes

2017-02-02 15:01 UTC, SamVerschueren commented on package.json
> +  "_args": [
Revert the `package.json`

2017-02-02 15:01 UTC, SamVerschueren commented on readme.md
> +### decompressTarbz()(buf)
Revert the name to `input` and add an extra `options` parameter

`decompressTarbz()(input, [options])`

Also document the new `options` object by pointing to the `options` parameter of `decompress-tar`. The last one has to wait untill the other PR is merged though.

2017-02-02 16:42 UTC, SamVerschueren requested changes

2017-02-02 16:42 UTC, SamVerschueren commented on readme.md
> +
Add extra line here.

2017-02-10 08:48 UTC, Xflofoxx commented on readme.md
> +
Done

2017-04-25 10:16 UTC, sindresorhus commented
Closing as `decompress-tar` doesn't have any options.

2017-04-25 10:16 UTC, closed without merging